apiVersion: apps/v1
kind: Deployment
metadata:
  name: rps
  labels:
    app: rps
spec:
  selector:
    matchLabels:
      app: rps
      name: rps
  template:
    # Pod definition starts here
    metadata:
      labels:
        app: rps
        name: rps
    spec:
      containers:
        - name: rps
          image: raymondfanglimin/rps:build-github.run_number
---
apiVersion: v1
kind: Service
metadata:
  name: rps
spec:
  type: NodePort
  selector:
    app: rps
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080

